<?php

/**
 * @file
 * responsive_videos.module
 */

/**
 * Implements hook_field_info().
 *
 */
function responsive_videos_field_info() {
  return array(
    'responsive_videos_embed' => array(
      'label' => t('Video Embed'),
      'description' => t('Video embed code.'),
      'default_widget' => 'responsive_videos_iframe',
      'default_formatter' => 'responsive_videos_wrapper',
    ),
  );
}

/**
 * Implements hook_field_validate().
 *
 */
function responsive_videos_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  foreach ($items as $delta => $item) {
    if (!empty($item['embed'])) {
      if (!preg_match('#(?:<iframe[^>]*)(?:(?:/>)|(?:>.*?</iframe>))#i', $item['embed'])) {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'responsive_videos_invalid',
          'message' => t('Please make sure your embed code is properly formatted.'),
        );
      }
    }
  }
}

/**
 * Implements hook_field_is_empty().
 *
 */
function responsive_videos_field_is_empty($item, $field) {
  return empty($item['embed']);
}

/**
 * Implements hook_field_formatter_info().
 *
 */
function responsive_videos_field_formatter_info() {
  return array(
    'responsive_videos_wrapper' => array(
      'label' => t('Responsive'),
      'field types' => array('responsive_videos_embed'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 *
 */
function responsive_videos_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'responsive_videos_wrapper':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#type' => 'html_tag',
          '#tag' => 'div',
          '#attributes' => array(
            'class' => 'video-container',
          ),
          '#value' => $item['embed'],
          '#attached' => array(
            'css' => array(
              'data' => drupal_get_path('module', 'responsive_videos') . '/css/responsive_videos.css',
              )
            ),
        );
      }
      break;
  }

  return $element;
}

/**
 * Implements hook_field_widget_info().
 *
 */
function responsive_videos_field_widget_info() {
  return array(
    'responsive_videos_iframe' => array(
      'label' => t('iFrame'),
      'field types' => array('responsive_videos_embed'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function responsive_videos_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $value = isset($items[$delta]['embed']) ? $items[$delta]['embed'] : '';

  $widget = $element;
  $widget['#delta'] = $delta;

  switch ($instance['widget']['type']) {
    case 'responsive_videos_iframe':
      $widget += array(
        '#type' => 'textarea',
        '#default_value' => $value,
        '#rows' => 3,
      );

      $widget['#description'] = t('Paste in the complete iFrame embed code from YouTube or Vimeo');
      break;
  }

  $element['embed'] = $widget;
  return $element;
}

/**
 * Implements hook_field_widget_error().
 *
 */
function responsive_videos_field_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
    case 'responsive_videos_invalid':
      form_error($element, $error['message']);
      break;
  }
}

/**
 * Implements template_preprocess_field().
 *
 */
function responsive_videos_preprocess_field(&$variables, $hook) {
  if ($variables['element']['#field_type'] == 'text_with_summary' || 'text_long') {
    $pattern = '#(?:<iframe[^>]*)(?:(?:/>)|(?:>.*?</iframe>))#i';
    if (isset($variables['items']['0']['#markup'])) {
      if (preg_match_all($pattern, $variables['items']['0']['#markup'], $output)) {
        foreach ($output[0] as $embed) {
          // check that the iframe is from youtube or vimeo
          if (strpos($embed, 'youtube') == false && strpos($embed, 'vimeo') == false) {
            continue;
          }
          $variables['items']['0']['#markup'] = str_replace($embed, '<div class="video-container">' . $embed . '</div>', $variables['items']['0']['#markup']);
        }
        $css = array(
          '#attached' => array(
            'css' => array(
              'data' => drupal_get_path('module', 'responsive_videos') . '/css/responsive_videos.css',
              )
            ),
          );
        drupal_render($css);
      }
    }
  }
}
